apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 5
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: yomeshbarod/healthcare:1
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  selector:
    app: healthcare
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30007
